version: '3.8'
services:
  cowsay:
    build: .
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
