version: '3.8'
services:
  cowsay:
    build: .
    ports:
      - "${COWSAY_HOST_PORT:-0}:80"  # Use dynamic port assignment, fallback to random if not set
    restart: always
    environment:
      - PORT=80  # Internal container port stays 80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
